# ============================================================
# FullFillX Web - Builder
# ============================================================

FROM node:26.7-alpine3.23 AS builder

WORKDIR /app

ARG VITE_API_URL=http://fulfillx-api:3000
ENV VITE_API_URL=${VITE_API_URL}

# Install pnpm
RUN npm install -g pnpm@11.22.0

# Workspace configuration
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Frontend
COPY apps/web ./apps/web

# Build frontend
RUN pnpm install --frozen-lockfile
RUN VITE_API_URL=${VITE_API_URL} pnpm --filter web build


# ============================================================
# FullFillX Web - Production
# ============================================================

FROM nginx:alpine AS production

# Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy React/Vite build
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

# Nginx configuration
COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
